@FoodShoppingAPI_HostAddress = http://localhost:5267

###
GET {{FoodShoppingAPI_HostAddress}}/api/foods?category=Fruit

### 
GET {{FoodShoppingAPI_HostAddress}}/api/foods/13

###
PUT {{FoodShoppingAPI_HostAddress}}/api/foods/13
Content-Type: application/json
{
  "name": "Bacon Pie",
  "price": 5,
  "quantity": 12,
  "categoryId": 13,
  "description": "Pie with bacon strips"
}

###
POST {{FoodShoppingAPI_HostAddress}}/api/foods
Content-Type: application/json

{
  "name": "Yoghurt",
  "price": 2.3,
  "quantity": 90,
  "categoryId": 12,
  "description": "A dairy product"
}

### 
DELETE {{FoodShoppingAPI_HostAddress}}/api/foods/12



    